export const data = [
  {
    title: 'Product1',
    url: 'https://picsum.photos/id/10/200/300',
    price: 100,
    details: 'This is details for  Product1',
    cart: 4,
  },
  {
    title: 'Product2',
    url: 'https://picsum.photos/id/20/200/300',
    price: 100,
    details: 'This is details for  Product2',
    cart: 4,
  },
  {
    title: 'Product3',
    url: 'https://picsum.photos/id/30/200/300',
    price: 100,
    details: 'This is details for  Product3',
    cart: 4,
  },
  {
    title: 'Product4',
    url: 'https://picsum.photos/id/40/200/300',
    price: 100,
    details: 'This is details for  Product4',
    cart: 4,
  },
  {
    title: 'Product5',
    url: 'https://picsum.photos/id/50/200/300',
    price: 100,
    details: 'This is details for  Product5',
    cart: 4,
  },
  {
    title: 'Product6',
    url: 'https://picsum.photos/id/60/200/300',
    price: 100,
    details: 'This is details for  Product6',
    cart: 4,
  },
  {
    title: 'Product7',
    url: 'https://picsum.photos/id/70/200/300',
    price: 100,
    details: 'This is details for  Product7',
    cart: 4,
  },
  {
    title: 'Product8',
    url: 'https://picsum.photos/id/80/200/300',
    price: 100,
    details: 'This is details for  Product8',
    cart: 4,
  },
  {
    title: 'Product9',
    url: 'https://picsum.photos/id/90/200/300',
    price: 100,
    details: 'This is details for  Product9',
    cart: 4,
  },
  {
    title: 'Product10',
    url: 'https://picsum.photos/id/100/200/300',
    price: 100,
    details: 'This is details for  Product10',
    cart: 4,
  },
];
