name: Install dependencies and run project

on:
  push:
    branches:
      - main
      - master
    workflow_dispatch:
jobs:
  # Install dependecies using yarn
  install-dependecies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Set up Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          cache: yarn
      - name: Install packages-libraries
        run: yarn
      # - name: pod installations
      #   run: cd ios && pod install
  # Perform android build/bundle
  build-android:
    needs: install-dependecies
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
